---
- name: update locale-gen
  command: locale-gen {{ lang }}.UTF-8

- name: update locale
  command: update-locale LANG={{ lang }}.UTF-8

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata