---

##
# Ansible playbook that installs PostgreSQL server
##

- hosts: databases
  sudo: yes
  gather_facts: yes
  vars:
    postgresql_version: 9.1
    postgresql_conf_path: /etc/postgresql/$postgresql_version/main
    postgresql_unix_socket_directory: /var/run/postgresql
    postgresql_listen_port: 5432
    postgresql_listen_address: '127.0.0.1'
    postgresql_cluster_encoding: ru_RU.UTF-8
  tasks:
  - include: tasks/setup-postgresql.yml
  handlers:
  - include: handlers/postgresql.yml
