---
  - name: ensure python-software-properties is installed
    apt: pkg=python-software-properties state=installed

  - name: ensure nginx official repository present
    apt_repository: repo=ppa:nginx/stable

  - name: install nginx
    apt: update_cache=yes name=nginx state=installed force=yes

  - name: write nginx.conf
    action: template src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
      - restart nginx

  - name: delete default vhost
    file: path=/etc/nginx/sites-enabled/default state=absent
    only_if: "$delete_default_vhost"
    notify:
      - restart nginx
