---
  - name: ensure nginx official repository present
    apt_repository: repo=ppa:nginx/stable
    when: ansible_os_family != "Debian"

  - name: install nginx
    apt: update_cache=yes name=nginx state=installed force=yes

  - name: write nginx.conf
    action: template src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
      - restart nginx

  - name: delete default vhost
    file: path=/etc/nginx/sites-enabled/default state=absent
    when: $delete_default_vhost
    notify:
      - restart nginx
