---
- name: create locale.gen
  template: src=templates/locale.gen.j2 dest=/etc/locale.gen
  when: lang is defined
  notify:
    - update locale-gen

- name: configure locale (with UTF-8 charset)
  template: src=templates/locale.j2 dest=/etc/default/locale
  when: lang is defined
  notify:
    - update locale
