---
  - name: ensure php-fpm repository present (Ubuntu 10.04)
    apt_repository: repo=ppa:brianmercer/php
    when: ansible_lsb.codename == "lucid"

  - name: install php5-fpm
    apt: name=php5-fpm force=yes

  - name: ensure PHP packages are installed
    apt: pkg={{ item }} force=yes
    with_items: $modules
    notify:
      - restart php5-fpm

  - name: delete default pool
    action: file path=/etc/php5/fpm/pool.d/www.conf state=absent
    when: delete_default_pool
    notify:
      - restart php5-fpm
