---
  - name: ensure yii path exists
    file: path=$yii_path mode=755 group=www-data owner=www-data state=directory recurse=yes

  - name: ensure yii repo is present
    git: repo=$yii_repo version=$yii_version force=yes dest=$yii_path depth=1

  - name: set owner for yii
    sudo: yes
    file: path=$yii_path group=www-data owner=www-data state=directory recurse=yes
